"""empty message

Revision ID: 2ce6b0d02ebc
Revises: b32ca1080fac
Create Date: 2020-11-06 20:43:24.705715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ce6b0d02ebc'
down_revision = 'b32ca1080fac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('finish_time', sa.DateTime(), nullable=True))
    op.drop_column('record', 'deadline')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('deadline', mysql.DATETIME(), nullable=True))
    op.drop_column('record', 'finish_time')
    # ### end Alembic commands ###
