"""empty message

Revision ID: 921645635396
Revises: 8eeabdcc99b0
Create Date: 2020-11-19 18:54:48.870872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921645635396'
down_revision = '8eeabdcc99b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('tag', sa.Text(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'tag')
    # ### end Alembic commands ###
