"""empty message

Revision ID: b32ca1080fac
Revises: 3508d6560c86
Create Date: 2020-11-06 20:33:36.738861

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b32ca1080fac'
down_revision = '3508d6560c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
